name: Call Reusable Workflow

on:
  push:
    branches:
      - main

env:
  REUSABLE_WORKFLOW: TBALSTM/STM32_AWS_CDK/.github/workflows/update-submodule.yml@main
  SUBMODULE: AED

jobs:
  call-reusable-workflow:
    concurrency:
      group: reusable-workflow-${{ github.ref }}
      cancel-in-progress: true
    uses: ${{ env.REUSABLE_WORKFLOW }}
    with:
      submodule_name: ${{ env.SUBMODULE }}
    secrets:
      personal_access_token: ${{ secrets.GA_TOKEN }}