name: Call Reusable Workflow

on:
  push:
    branches:
      - main
    path-ignore:
      - 'templates/**'
      - '**/*.md'


jobs:
  call-reusable-workflow:
    concurrency:
      group: reusable-workflow-${{ github.ref }}
      cancel-in-progress: true
    uses: TBALSTM/STM32_AWS_CDK/.github/workflows/update-submodule.yml@main
    with:
      submodule_name: AED
    secrets:
      personal_access_token: ${{ secrets.GA_TOKEN }}