name: Call Reusable Workflow

on:
  push:
    branches:
      - main


jobs:
  call-reusable-workflow:
    uses: TBALSTM/STM32_AWS_CDK/.github/workflows/update-submodule.yml@main
    with:
      submodule_name: "AED"